// Source Code Generated by TRAXMOD Converter
// Copyright (c) 2005, K9spud LLC.

#ifndef ORDERDATA_H
#define ORDERDATA_H

#define NUMORDERS 73

extern void Pattern0(void);
extern void Pattern1(void);
extern void Pattern2(void);
extern void Pattern3(void);
extern void Pattern4(void);
extern void Pattern5(void);
extern void Pattern6(void);
extern void Pattern7(void);
extern void Pattern8(void);
extern void Pattern9(void);
extern void Pattern10(void);
extern void Pattern11(void);
extern void Pattern12(void);
extern void Pattern13(void);
extern void Pattern14(void);
extern void Pattern15(void);
extern void Pattern16(void);
extern void Pattern17(void);
extern void Pattern18(void);
extern void Pattern19(void);
extern void Pattern20(void);
extern void Pattern21(void);
extern void Pattern22(void);
extern void Pattern23(void);
extern void Pattern24(void);
extern void Pattern25(void);
extern void Pattern26(void);
extern void Pattern27(void);
extern void Pattern28(void);
extern void Pattern29(void);
extern void Pattern30(void);
extern void Pattern31(void);
extern void Pattern32(void);
extern void Pattern33(void);
extern void Pattern34(void);
extern void Pattern35(void);
extern void Pattern36(void);
extern void Pattern37(void);
extern void Pattern38(void);
extern void Pattern39(void);
extern void Pattern40(void);
extern void Pattern41(void);
extern void Pattern42(void);
extern void Pattern43(void);
extern void Pattern44(void);
extern void Pattern45(void);
extern void Pattern46(void);
extern void Pattern47(void);

inline unsigned int getPattern(unsigned int iOrder)
{
  switch(iOrder)
  {
    default:
    case 0:
      return (unsigned int)(&Pattern39) + ((unsigned int)(&Pattern39) >> 1);

    case 1:
      return (unsigned int)(&Pattern39) + ((unsigned int)(&Pattern39) >> 1);

    case 2:
      return (unsigned int)(&Pattern1) + ((unsigned int)(&Pattern1) >> 1);

    case 3:
      return (unsigned int)(&Pattern0) + ((unsigned int)(&Pattern0) >> 1);

    case 4:
      return (unsigned int)(&Pattern5) + ((unsigned int)(&Pattern5) >> 1);

    case 5:
      return (unsigned int)(&Pattern5) + ((unsigned int)(&Pattern5) >> 1);

    case 6:
      return (unsigned int)(&Pattern7) + ((unsigned int)(&Pattern7) >> 1);

    case 7:
      return (unsigned int)(&Pattern6) + ((unsigned int)(&Pattern6) >> 1);

    case 8:
      return (unsigned int)(&Pattern5) + ((unsigned int)(&Pattern5) >> 1);

    case 9:
      return (unsigned int)(&Pattern5) + ((unsigned int)(&Pattern5) >> 1);

    case 10:
      return (unsigned int)(&Pattern8) + ((unsigned int)(&Pattern8) >> 1);

    case 11:
      return (unsigned int)(&Pattern9) + ((unsigned int)(&Pattern9) >> 1);

    case 12:
      return (unsigned int)(&Pattern2) + ((unsigned int)(&Pattern2) >> 1);

    case 13:
      return (unsigned int)(&Pattern2) + ((unsigned int)(&Pattern2) >> 1);

    case 14:
      return (unsigned int)(&Pattern3) + ((unsigned int)(&Pattern3) >> 1);

    case 15:
      return (unsigned int)(&Pattern3) + ((unsigned int)(&Pattern3) >> 1);

    case 16:
      return (unsigned int)(&Pattern10) + ((unsigned int)(&Pattern10) >> 1);

    case 17:
      return (unsigned int)(&Pattern4) + ((unsigned int)(&Pattern4) >> 1);

    case 18:
      return (unsigned int)(&Pattern11) + ((unsigned int)(&Pattern11) >> 1);

    case 19:
      return (unsigned int)(&Pattern11) + ((unsigned int)(&Pattern11) >> 1);

    case 20:
      return (unsigned int)(&Pattern12) + ((unsigned int)(&Pattern12) >> 1);

    case 21:
      return (unsigned int)(&Pattern12) + ((unsigned int)(&Pattern12) >> 1);

    case 22:
      return (unsigned int)(&Pattern13) + ((unsigned int)(&Pattern13) >> 1);

    case 23:
      return (unsigned int)(&Pattern14) + ((unsigned int)(&Pattern14) >> 1);

    case 24:
      return (unsigned int)(&Pattern15) + ((unsigned int)(&Pattern15) >> 1);

    case 25:
      return (unsigned int)(&Pattern16) + ((unsigned int)(&Pattern16) >> 1);

    case 26:
      return (unsigned int)(&Pattern19) + ((unsigned int)(&Pattern19) >> 1);

    case 27:
      return (unsigned int)(&Pattern17) + ((unsigned int)(&Pattern17) >> 1);

    case 28:
      return (unsigned int)(&Pattern18) + ((unsigned int)(&Pattern18) >> 1);

    case 29:
      return (unsigned int)(&Pattern18) + ((unsigned int)(&Pattern18) >> 1);

    case 30:
      return (unsigned int)(&Pattern20) + ((unsigned int)(&Pattern20) >> 1);

    case 31:
      return (unsigned int)(&Pattern21) + ((unsigned int)(&Pattern21) >> 1);

    case 32:
      return (unsigned int)(&Pattern23) + ((unsigned int)(&Pattern23) >> 1);

    case 33:
      return (unsigned int)(&Pattern23) + ((unsigned int)(&Pattern23) >> 1);

    case 34:
      return (unsigned int)(&Pattern24) + ((unsigned int)(&Pattern24) >> 1);

    case 35:
      return (unsigned int)(&Pattern24) + ((unsigned int)(&Pattern24) >> 1);

    case 36:
      return (unsigned int)(&Pattern25) + ((unsigned int)(&Pattern25) >> 1);

    case 37:
      return (unsigned int)(&Pattern25) + ((unsigned int)(&Pattern25) >> 1);

    case 38:
      return (unsigned int)(&Pattern31) + ((unsigned int)(&Pattern31) >> 1);

    case 39:
      return (unsigned int)(&Pattern31) + ((unsigned int)(&Pattern31) >> 1);

    case 40:
      return (unsigned int)(&Pattern32) + ((unsigned int)(&Pattern32) >> 1);

    case 41:
      return (unsigned int)(&Pattern32) + ((unsigned int)(&Pattern32) >> 1);

    case 42:
      return (unsigned int)(&Pattern36) + ((unsigned int)(&Pattern36) >> 1);

    case 43:
      return (unsigned int)(&Pattern35) + ((unsigned int)(&Pattern35) >> 1);

    case 44:
      return (unsigned int)(&Pattern37) + ((unsigned int)(&Pattern37) >> 1);

    case 45:
      return (unsigned int)(&Pattern37) + ((unsigned int)(&Pattern37) >> 1);

    case 46:
      return (unsigned int)(&Pattern32) + ((unsigned int)(&Pattern32) >> 1);

    case 47:
      return (unsigned int)(&Pattern32) + ((unsigned int)(&Pattern32) >> 1);

    case 48:
      return (unsigned int)(&Pattern34) + ((unsigned int)(&Pattern34) >> 1);

    case 49:
      return (unsigned int)(&Pattern33) + ((unsigned int)(&Pattern33) >> 1);

    case 50:
      return (unsigned int)(&Pattern38) + ((unsigned int)(&Pattern38) >> 1);

    case 51:
      return (unsigned int)(&Pattern38) + ((unsigned int)(&Pattern38) >> 1);

    case 52:
      return (unsigned int)(&Pattern26) + ((unsigned int)(&Pattern26) >> 1);

    case 53:
      return (unsigned int)(&Pattern22) + ((unsigned int)(&Pattern22) >> 1);

    case 54:
      return (unsigned int)(&Pattern27) + ((unsigned int)(&Pattern27) >> 1);

    case 55:
      return (unsigned int)(&Pattern28) + ((unsigned int)(&Pattern28) >> 1);

    case 56:
      return (unsigned int)(&Pattern29) + ((unsigned int)(&Pattern29) >> 1);

    case 57:
      return (unsigned int)(&Pattern30) + ((unsigned int)(&Pattern30) >> 1);

    case 58:
      return (unsigned int)(&Pattern40) + ((unsigned int)(&Pattern40) >> 1);

    case 59:
      return (unsigned int)(&Pattern41) + ((unsigned int)(&Pattern41) >> 1);

    case 60:
      return (unsigned int)(&Pattern44) + ((unsigned int)(&Pattern44) >> 1);

    case 61:
      return (unsigned int)(&Pattern42) + ((unsigned int)(&Pattern42) >> 1);

    case 62:
      return (unsigned int)(&Pattern42) + ((unsigned int)(&Pattern42) >> 1);

    case 63:
      return (unsigned int)(&Pattern43) + ((unsigned int)(&Pattern43) >> 1);

    case 64:
      return (unsigned int)(&Pattern43) + ((unsigned int)(&Pattern43) >> 1);

    case 65:
      return (unsigned int)(&Pattern42) + ((unsigned int)(&Pattern42) >> 1);

    case 66:
      return (unsigned int)(&Pattern42) + ((unsigned int)(&Pattern42) >> 1);

    case 67:
      return (unsigned int)(&Pattern45) + ((unsigned int)(&Pattern45) >> 1);

    case 68:
      return (unsigned int)(&Pattern45) + ((unsigned int)(&Pattern45) >> 1);

    case 69:
      return (unsigned int)(&Pattern46) + ((unsigned int)(&Pattern46) >> 1);

    case 70:
      return (unsigned int)(&Pattern46) + ((unsigned int)(&Pattern46) >> 1);

    case 71:
      return (unsigned int)(&Pattern45) + ((unsigned int)(&Pattern45) >> 1);

    case 72:
      return (unsigned int)(&Pattern47) + ((unsigned int)(&Pattern47) >> 1);

  }
}

#endif // ORDERDATA_H

