// Source Code Generated by TRAXMOD Converter
// Copyright (c) 2005, K9spud LLC.

#include "mixer.h"

extern void Sample1(void);
extern void Sample2(void);
extern void Sample3(void);
extern void Sample4(void);
extern void Sample5(void);
extern void Sample6(void);
extern void Sample7(void);
extern void Sample8(void);
extern void Sample10(void);
extern void Sample11(void);
extern void Sample12(void);
extern void Sample13(void);
extern void Sample14(void);
extern void Sample15(void);
extern void Sample16(void);

void SetSample(ChannelType* pChan, unsigned int iSample)
{
  switch(iSample)
  {
    case 0:
      return; // do nothing

    default:
    case 9:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
      pChan->bActive = 0;
      break;

    case 1:
      // # Moby/ATZ
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00000000;
      pChan->SDEnd =       0x00001150;
      pChan->bLoop = 0;
      break;

    case 2:
      //   --- m o b y --- atz
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00001180;
      pChan->SDLoopStart = 0x00005F40;
      pChan->SDEnd =       0x0000604C;
      pChan->bLoop = 1;
      break;

    case 3:
      // 07 april 91
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00006080;
      pChan->SDEnd =       0x00007182;
      pChan->bLoop = 0;
      break;

    case 4:
      // enjoy the tune !!!
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x000071C0;
      pChan->SDEnd =       0x00007E84;
      pChan->bLoop = 0;
      break;

    case 5:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00007EC0;
      pChan->SDEnd =       0x00009932;
      pChan->bLoop = 0;
      break;

    case 6:
      // hi to my friends.
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00009940;
      pChan->SDEnd =       0x0000B060;
      pChan->bLoop = 0;
      break;

    case 7:
      // special hello to
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x0000B080;
      pChan->SDLoopStart = 0x0000D280;
      pChan->SDEnd =       0x0000D3AC;
      pChan->bLoop = 1;
      break;

    case 8:
      // kougar / dreamdealers
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x0000D3C0;
      pChan->SDEnd =       0x0000E088;
      pChan->bLoop = 0;
      break;

    case 10:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x0000E0C0;
      pChan->SDEnd =       0x0000FFCA;
      pChan->bLoop = 0;
      break;

    case 11:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00010000;
      pChan->SDEnd =       0x000129FA;
      pChan->bLoop = 0;
      break;

    case 12:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00012A00;
      pChan->SDLoopStart = 0x00014100;
      pChan->SDEnd =       0x00014180;
      pChan->bLoop = 1;
      break;

    case 13:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00014180;
      pChan->SDEnd =       0x000155CC;
      pChan->bLoop = 0;
      break;

    case 14:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00015600;
      pChan->SDEnd =       0x00017CAC;
      pChan->bLoop = 0;
      break;

    case 15:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x00017CC0;
      pChan->SDEnd =       0x0001AEFA;
      pChan->bLoop = 0;
      break;

    case 16:
      // 
      pChan->bActive = 1;
      pChan->bSD = 1;
      pChan->SDLoc =       0x0001AF00;
      pChan->SDLoopStart = 0x0001AFC0;
      pChan->SDEnd =       0x0001AFDE;
      pChan->bLoop = 1;
      break;

  }
  pChan->iSample = iSample;

}
